<?php

/**
 * @file
 * The module file for ftmeet.
 */

function ftmeet_init() {
  drupal_add_css(drupal_get_path('module', 'ftmeet') . '/css/ftmeet.css', array('group' => CSS_DEFAULT, 'every_page' => TRUE));
}

/**
 * Implements hook_menu()
 */
function ftmeet_menu() {
  $items = array();
  $items['speaker/%user'] = array(
    'page callback' => 'ftmeet_speaker_callback',
    'page arguments' => array(1),
    'access callback' => 'ftmeet_speaker_access_callback',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );
  $items['profile/%user'] = array(
    'page callback' => 'ftmeet_profile_callback',
    'page arguments' => array(1),
    'access callback' => 'ftmeet_profile_access_callback',
    'access arguments' => array(1),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Access callback for speaker/%user.
 *
 * Function to check if user exists in system.
 *
 * @param  object $user
 *   User object
 * @return bool
 *   TRUE if access is allowed, else FALSE.
 */
function ftmeet_speaker_access_callback($user) {
  if (isset($user) && in_array('speaker', $user->roles)) {
    return TRUE;
  }
  return FALSE;
}

/**
 * Callback function for speaker/%user.
 *
 * @param  object $user
 *   The user object of the speaker.
 * @return array $page
 *   A renderable array of output.
 */
function ftmeet_speaker_callback($user) {

  $profile = profile2_load_by_user($user->uid, 'main');

  $lang = field_language('profile2', $profile, 'field_full_name');
  $speaker['full_name'] = ($profile->field_full_name[$lang][0]['value']) ? $profile->field_full_name[$lang][0]['value'] : '';
  drupal_set_title($speaker['full_name']);

  $lang = field_language('profile2', $profile, 'field_description');
  $speaker['description'] = ($profile->field_description) ? $profile->field_description[$lang][0]['value'] : '';

  $lang = field_language('profile2', $profile, 'field_facebook_profile');
  $facebook_title = ($profile->field_facebook_profile) ? $profile->field_facebook_profile[$lang][0]['title'] : '';
  $facebook_link = ($profile->field_facebook_profile) ? $profile->field_facebook_profile[$lang][0]['url'] : '';
  $speaker['facebook'] = l($facebook_title, $facebook_link, array('attributes' => array('target'=>'_blank')));

  $lang = field_language('profile2', $profile, 'field_profile_image');
  $speaker['image'] = ($profile->field_profile_image) ? $profile->field_profile_image[$lang][0]['uri'] : '';

  $page['#theme'] = 'ftmeet_speaker';
  $page = array(
    '#theme' => 'ftmeet_speaker',
    '#speaker' => $speaker,
  );

  return $page;
}

/**
 * Access callback for profile/%user.
 *
 * Function to check if user exists in system.
 *
 * @param  object $user
 *   User object
 * @return bool
 *   TRUE if access is allowed, else FALSE.
 */
function ftmeet_profile_access_callback($user) {
  if (isset($user) && !in_array('speaker', $user->roles)) {
    return TRUE;
  }
  elseif (isset($user) && in_array('speaker', $user->roles)) {
    drupal_goto('speaker/' . $user->uid);
  }
  return FALSE;
}

/**
 * Callback function for profile/%user.
 *
 * @param  object $user
 *   The user object of the speaker.
 * @return array $page
 *   A renderable array of output.
 */
function ftmeet_profile_callback($user) {

  $profile = profile2_load_by_user($user->uid, 'main');

  $lang = field_language('profile2', $profile, 'field_full_name');
  $speaker['full_name'] = ($profile->field_full_name[$lang][0]['value']) ? $profile->field_full_name[$lang][0]['value'] : '';
  ($speaker['full_name'] != '' ) ? drupal_set_title($speaker['full_name']) : drupal_set_title($user->name);

  $lang = field_language('profile2', $profile, 'field_description');
  $speaker['description'] = ($profile->field_description) ? $profile->field_description[$lang][0]['value'] : '';

  $lang = field_language('profile2', $profile, 'field_facebook_profile');
  $facebook_title = ($profile->field_facebook_profile) ? $profile->field_facebook_profile[$lang][0]['title'] : '';
  $facebook_link = ($profile->field_facebook_profile) ? $profile->field_facebook_profile[$lang][0]['url'] : '';
  $speaker['facebook'] = l($facebook_title, $facebook_link, array('attributes' => array('target'=>'_blank')));

  $lang = field_language('profile2', $profile, 'field_profile_image');
  $speaker['image'] = ($profile->field_profile_image) ? $profile->field_profile_image[$lang][0]['uri'] : '';

  $page['#theme'] = 'ftmeet_speaker';
  $page = array(
    '#theme' => 'ftmeet_speaker',
    '#speaker' => $speaker,
  );

  return $page;
}

/**
 * Implements hook_theme().
 */
function ftmeet_theme() {
  return array(
    'ftmeet_speaker' => array(
      'variables' => array(
        'speaker' => 'speaker',
      ),
      'template' => 'templates/ftmeet-speaker',
    ),
    'node__session' => array(
      'render element' => 'content',
      'base hook' => 'node',
      'template' => 'templates/node--session',
    )
  );
}

/**
 * Implements hook_preprocess_node().
 */
function ftmeet_preprocess_node(&$variables) {
  if (isset($variables['type']) && $variables['type'] === 'session') {
    if ($variables['view_mode'] == 'full') {
      $profile = profile2_load_by_user($variables['field_speaker'][0]['user']->uid, 'main');
      $lang = field_language('profile2', $profile, 'field_full_name');
      $variables['full_name'] = $profile->field_full_name[$lang][0]['value'];
    }
    else {
      $profile = profile2_load_by_user($variables['field_speaker']['und'][0]['uid'], 'main');
      $lang = field_language('profile2', $profile, 'field_full_name');
      $variables['full_name'] = $profile->field_full_name[$lang][0]['value'];
    }
  }
}

/**
 * Implements hook_page_alter().
 */
function ftmeet_page_alter(&$page) {
  global $user;
  global $is_front;
  $arg0 = arg(0);
  $arg1 = arg(1);
  $arg2 = arg(2);
  if ($arg0 == 'user' && is_numeric($arg1) && $arg2 == '') {
    drupal_goto('profile/' . $user->uid);
  }
  if (drupal_is_front_page()) {
    drupal_set_title('Freethinkers Meet | Dare to think');
  }

}

/**
 * Implements_hook_user_login().
 */
function ftmeet_user_login($account) {
  $user = user_load($account['uid']);
  $profile = profile2_create(array('type' => 'main', 'uid' => $account['uid']));
  $profile->field_full_name[LANGUAGE_NONE][0]['value'] = $user->name;
  $user->name = str_replace(' ', '', $user->name);
  $user->name = strtolower(($user->name));
  user_save($user);
  if (isset($user->picture->uri)) {
    $image = file_get_contents($user->picture->uri);
    $file = file_save_data($image, '', FILE_EXISTS_RENAME);
    $profile->field_profile_image[LANGUAGE_NONE][0] = (array)$file;
  }
  profile2_save($profile);
}
